### ISSUE TITLE
Please expose major version and release with typings

### ISSUE THREAD

**Issue by krzema12** [entrostat/git-secret-action#6]
Hi @Kerren-Entrostat!

As a follow up after https://github.com/entrostat/git-secret-action/pull/3, in order to consume the typings in one of our projects, I'd like to ask you to make your action:

* expose a major version tag/branch (see a similar ticket: https://github.com/superfly/flyctl-actions/issues/33), in your case a `v4` tag/branch pointing currently to `v4.0.2`. It's in line with GitHub recommendations
* have a release that points to a commit with the typings

CC @LeoColman 

Thanks!
Piotr

**Comment by Kerren-Entrostat** [comment]
Hi @krzema12

I've created the `v4` tag so we should be good there.

For the release, I updated this one with the commit SHA: https://github.com/entrostat/git-secret-action/releases/tag/v4.0.1

Please let me know if there are any other suggestions!
